baseURL = "https://reconcept.nl/dev/"
languageCode = "nl-nl"
defaultContentLanguage = "nl"
title = "Reconcept"
theme = "reconcept"
[params]
  featured_image = "featured_image.jpg"

[module]
  [[module.mounts]]
    source = "assets" 
    target = "assets"
  [[module.mounts]]
    source = "node_modules/jquery-lite/dist"
    target = "static/jquery-lite"