baseURL = "https://reconcept.nl/"
languageCode = "en-us"
title = "Reconcept"
theme = "reconcept"
[params]
  featured_image = "featured_image.jpg"

[module]
  [[module.mounts]]
    source = "assets" 
    target = "assets"